/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 aston_martin.glb --transform 
Files: aston_martin.glb [10.97MB] > C:\Front End\Vite React\three-js-practice\public\models\aston_martin-transformed.glb [804.36KB] (93%)
Author: Black Snow (https://sketchfab.com/BlackSnow02)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/aston-martin-db11-0ce56f01b1ff40b3a4e36bc56873dbc7
Title: Aston Martin db11
*/

import React, { useLayoutEffect, useRef, useEffect } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import { gsap } from "gsap";
import { useThree } from '@react-three/fiber'


function d2r(degrees) {
  return degrees * (Math.PI / 180);
}

export function Aston(props) {
  const { nodes, materials } = useGLTF('./models/aston_martin_transformed.glb')
  const Car = useRef();
  const scroll = useScroll();
  const tl = useRef();
  const tlInit = useRef();
  

  

  useLayoutEffect(() => {
    tlInit.current = gsap.timeline({ defaults: { duration: 4, ease: 'power4.out' } });

    tlInit.current
      .to(Car.current.position, { y: -1.3 })
  }, [])

  useFrame((state, delta) => {
    tl.current.seek(scroll.offset * tl.current.duration())
  })

  useLayoutEffect(() => {
  

    tl.current = gsap.timeline({ defaults: { duration: .8, ease: 'none' } })

    tl.current
    .to(Car.current.position, {
      x: -4.5,
      y: -0.28,
      z: -9.5
    }, 0.2)
    .to(Car.current.rotation, {
      x: d2r(90),
      y: d2r(270),
      z: d2r(79.60)
    }, 0.2)

    .to(Car.current.position, {
      x: 3.520,
      y: 0,
      z: -7.5
    }, 2)
    .to(Car.current.rotation, {
      x: d2r(20.40),
      y: d2r(314.80),
      z: d2r(6)
    }, 2)   
    .to(Car.current.position, {
      x: 3.520,
      y: 0,
      z: -7.5
    }, 3)
    .to(Car.current.rotation, {
      x: d2r(20.40),
      y: d2r(314.80),
      z: d2r(6)
    }, 3)   


  }, [])
  return (

    // <group {...props} dispose={null} ref={Car} position={[-3,0,-0.5]} rotation={[d2r(0), -d2r(90), d2r(0)]} castShadow>
    <group {...props} dispose={null} ref={Car} position={[0, -6.4, -9.5]} rotation={[d2r(90), d2r(180), 0]} >

      <mesh geometry={nodes.amdb11_wheel_03_amdb11_mirror_0.geometry} material={materials.PaletteMaterial002} position={[0.962, 0.376, 1.302]} rotation={[-Math.PI / 2, 0, 0]}>

      </mesh>
      <mesh geometry={nodes.amdb11_bumperbar_F_etkc_0.geometry} material={materials.PaletteMaterial002} rotation={[-Math.PI / 2, 0, 0]} >

      </mesh>
      <mesh geometry={nodes.amdb11_headlight_R_amdb11_signal_R_0.geometry} material={materials.PaletteMaterial003} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.amdb11_headlight_L_amdb11_signal_L_0.geometry} material={materials.PaletteMaterial004} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.amdb11_headlightglass_R_amdb11_glass_0.geometry} material={materials.PaletteMaterial005} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.amdb11_taillight_L_amdb11_signal_RL_0.geometry} material={materials.PaletteMaterial006} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./models/aston_martin_transformed.glb')
